name: ci-only

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Initial Setup
        run: |
          sudo apt-get install jq
      - name: Validate Images
        run: |
          jq empty functions.json
          jq empty templates.json
